name: Deploy to Firebase Hosting on push to main

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run build commands (if applicable)
      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build  # Adjust if necessary

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for repo access
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEWFIREBASE_85871 }}  # Firebase service account key
          channelId: live  # Production channel (can be changed for different environments)
          projectId: newfirebase-85871  # Your Firebase project ID
